version: '3.8'

services:
  nginx:
    image: nginx:1.21.6
    restart: always
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/services/:/etc/nginx/proxymate
